
name: test
on:
  workflow_dispatch:
  push:
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@5af77018d925462d101d85b349f65d11cc1b8a9b

      - name: do something
        run: ping google.com -c 10 || true
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@a25fd8734f4a4a18a3ffaa887330ab80fcdc3db6
        with:
          fail-on-diff: "true"
          create-pr: "true"
