
name: test
on:
  workflow_dispatch
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@be3bd3bdbc306bc9ec3a040005795a4f354d06ef

      - name: do something
        run: sleep 5; touch yo
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@824eb083845f92e84c63daf26337f82ccbce224d
        with:
          fail-on-diff: "true"
          create-pr: "true"
