
name: test
on:
  workflow_dispatch:
  push:
  
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@6423ef93562d8d14bbd46bb6c297b1b80ff69399

      - name: do something
        run: sleep 5; touch yo
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@e3ca5f6288a675f7c1616cb2d4ce43af757f9de5
        with:
          fail-on-diff: "true"
          create-pr: "true"
