
name: test
on:
  workflow_dispatch:
  push:
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@a20ad76a0499e496865d7d016d48a53feb739abd

      - name: do something
        run: ping google.com -c 1 || touch foo
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@a61a6a1609d90a877fa5d06f9b9755e6c9d35f05
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail-on-diff: "false"
          create-pr: "true"
