
name: test
on:
  workflow_dispatch:
  push:
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@0f77d1f25bb9b7dc62f4fa802bf3eb9e1b50fd83

      - name: do something
        run: ping google.com -c 1 || touch foo
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@4c016c7c706a6dc26f93a7a84c53ae046e1699c7
        with:
          fail-on-diff: "true"
          create-pr: "true"
