
name: test
on:
  workflow_dispatch:
  push:
  
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@be3bd3bdbc306bc9ec3a040005795a4f354d06ef

      - name: do something
        run: sleep 5; touch yo
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@bfd9d4c22296ba2179c91fcff868244840cfbab0
        with:
          fail-on-diff: "true"
          create-pr: "true"
