
name: test
on:
  workflow_dispatch:
  push:
  
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@6c79a13adb1931ff0e764dfb6e9233ba2b1bc83a

      - name: do something
        run: sleep 5; touch yo
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@3047c579fa947d056863115470486c5d7bb2f312
        with:
          fail-on-diff: "true"
          create-pr: "true"
