
name: test
on:
  workflow_dispatch:
  push:
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@37cc25bde2ab2c8e9a16b021082230e173641bea

      - name: do something
        run: ping google.com -c 1 || true
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@f35385a428b42a974b96f57504a033c3a5484717
        with:
          fail-on-diff: "true"
          create-pr: "true"
