
name: test
on:
  workflow_dispatch:
  push:
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@37cc25bde2ab2c8e9a16b021082230e173641bea

      - name: do something
        run: ping google.com -c 10 || true
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@ca6f572e86bd9b253d273e258b2ff39750b820a4
        with:
          fail-on-diff: "true"
          create-pr: "true"
