name: debug
on:
  workflow_dispatch:
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
    - shell: bash
    run: |
      docker run -d  alpine sleep infinity
      pstree -h
    #  - name: Debugging with ssh
    #    uses: lhotari/action-upterm@v1
