
name: test-tracee
on:
  workflow_dispatch:
  push:
  
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@be3bd3bdbc306bc9ec3a040005795a4f354d06ef

      - name: do something
        run: sleep 4; touch second
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@7312090afba752fcc9cec6dbd2ff1a685dd64e76
        with:
          fail-on-diff: "true"
          create-pr: "true"
