
name: second
on:
  workflow_dispatch:
  
jobs:
  xxx:
    name: xxx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Tracee
        uses: itaysk/tracee-action@be3bd3bdbc306bc9ec3a040005795a4f354d06ef

      - name: do something
        run: sleep 4; touch second
        
      - name: Stop Tracee
        uses: itaysk/tracee-action@bf8e0d990d00369ee782d8a8e1b6d1929e23c6c3
        with:
          fail-on-diff: "true"
          create-pr: "true"
