name: vulntest
on:
  workflow_dispatch:
  push:
jobs:
  one:
    name: one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: has vulnerabilities
        run: |
          jq --exit-status --arg sev 'MEDIUM' '[ .Results[].Vulnerabilities[].Severity ] | any($sev)' ${{ github.workspace }}/nodejs.trivy.json
          
      - name: has bad package
        run: |
          jq --exit-status --arg pkg 'jquery@3.3.9' '[ .Results[].Packages[].ID ] | any($pkg)' ${{ github.workspace }}/nodejs.trivy.json
